-- Query all constraints using INFORMATION_SCHEMA
SELECT 
    tc.CONSTRAINT_NAME, 
    tc.TABLE_NAME, 
    tc.CONSTRAINT_TYPE,
    ccu.COLUMN_NAME,
    rc.UNIQUE_CONSTRAINT_NAME as REFERENCED_CONSTRAINT,
    rcu.TABLE_NAME as REFERENCED_TABLE,
    rcu.COLUMN_NAME as REFERENCED_COLUMN
FROM 
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
LEFT JOIN 
    INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu 
    ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc 
    ON tc.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE rcu 
    ON rc.UNIQUE_CONSTRAINT_NAME = rcu.CONSTRAINT_NAME
WHERE 
    tc.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'FOREIGN KEY', 'UNIQUE')
ORDER BY 
    tc.TABLE_NAME, tc.CONSTRAINT_TYPE;